/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package herkastudetector;

public class App {

    String[][] ret;

    String[][] generaljRetet() {
        String[] elsoSor = {"kakis pelenka", "bokor", "pazsit"};
        String[] masodikSor = {"bokor", "AIDS-es tu", "uveg tormelek"};
        String[] harmadikSor = {"nejlon zacsko", "pazsit", "cigi csikk"};
        String[][] ret = {elsoSor, masodikSor, harmadikSor};
        return ret;
    }

    public static void main(String[] args) {
        App app = new App();
        app.ret = app.generaljRetet();

        HerkasTuHelper.printeldKiARetet(app.ret);

        System.out.println();

        System.out.println(HerkasTuHelper.holATu(app.ret));
    }
}
